name: mapping_machine
channels:
  - conda-forge
  - defaults
dependencies:
  - gensim=4.3.2
  - ipykernel=6.29.0
  - jupyter_core=5.7.1
  - jupyterlab=4.0.11
  - jupyterlab_server=2.25.2
  - levenshtein=0.23.0
  - nbconvert=7.14.2
  - notebook=7.0.7
  - numpy=1.26.3
  - openpyxl=3.1.2
  - pandas=2.2.0
  - pre-commit=3.6.0
  - psycopg2=2.9.9
  - python=3.9.18
  - rapidfuzz=3.6.1
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - sqlalchemy=2.0.25
  - pip:
      - pyarrow==15.0.0
      - spacy==3.4.4
      - thinc==8.1.12
      - typer==0.7.0
